### ISSUE TITLE
Name suggestion

### ISSUE THREAD

**Issue by yebai** [JuliaDiff/DifferentiationInterface.jl#123]
The current name looks OK but is a bit lengthy. Maybe ADInterface is a sensible option? It’s nice since its connection to ADTypes is clearer.

**Comment by gdalle** [comment]
Thanks for the suggestion!
We chose to follow the [package naming guidelines](https://pkgdocs.julialang.org/v1/creating-packages/#Package-naming-guidelines) on that point:

> 1. Avoid jargon. In particular, avoid acronyms unless there is minimal possibility of confusion.
>     It's ok to say USA if you're talking about the USA.
>     It's not ok to say PMA, even if you're talking about positive mental attitude.

> 4. Err on the side of clarity, even if clarity seems long-winded to you.
>    RandomMatrices is a less ambiguous name than RndMat or RMT, even though the latter are shorter.

Granted, AD is kind of borderline because it is a well-known acronym... but we may be biased after all. And since we want this package to be useful and discoverable for everyone, even people who don't know what the acronym AD usually stands for, we err on the side of caution.

If you find the package name too long, you can always do
```julia
import DifferentiationInterface as DI
```
