### ISSUE TITLE
Prepared sparse `hessian!` calls `prepare_gradient` at every invocation?

### ISSUE THREAD

**Issue by Vaibhavdixit02** [JuliaDiff/DifferentiationInterface.jl#376]
Trying to do some profiling on one of my usecases in Optimization.jl I observed that `hessian!` call with the extras being passed ends calling `prepare_gradient` on every invocation which is surprising, I am hitting this code path https://github.com/gdalle/DifferentiationInterface.jl/blob/main/DifferentiationInterface/src/sparse/hessian.jl#L117 -> https://github.com/gdalle/DifferentiationInterface.jl/blob/main/DifferentiationInterface/src/second_order/hvp_batched.jl#L145 -> https://github.com/gdalle/DifferentiationInterface.jl/blob/main/DifferentiationInterface/src/second_order/hvp.jl#L61 -> https://github.com/gdalle/DifferentiationInterface.jl/blob/main/DifferentiationInterface/src/first_order/gradient.jl#L82

**Comment by gdalle** [comment]
Yes indeed. That's because preparation is shared among four variants of the operator: in-place/out-of-place, with/without the value. For second-order operators, the variant "with value" also returns a first derivative: value and hessian would be a bit weird if I didn't return the gradient as well. So this is a performance tradeoff I make in order not to have four variants of the preparation syntax. What do you think?

**Comment by Vaibhavdixit02** [comment]
I would really like a way to avoid this, even if it's an internal API and not as convenient as hessian! call. Is there something I can use?

**Comment by gdalle** [comment]
Why do you want to avoid this? Where is it costing you?

**Comment by gdalle** [comment]
This is the same issue as #86, partially solved by #385
